
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA pigi DEFAULT CHARACTER SET UTF8;

SET SCHEMA 'PIGI';

CREATE DOMAIN pigi.Number AS INTEGER CONSTRAINT Number_Unsigned_Chk CHECK (VALUE >= 0);

CREATE TABLE pigi.Repository
(
	repositoryId INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	location CHARACTER VARYING NOT NULL,
	title CHARACTER(255) NOT NULL,
	description CHARACTER VARYING NOT NULL,
	CONSTRAINT Repository_PK PRIMARY KEY(repositoryId),
	CONSTRAINT Repository_UC UNIQUE(location)
);

CREATE TABLE pigi.Revision
(
	revisionId INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	author CHARACTER(255) NOT NULL,
	"date" TIMESTAMP NOT NULL,
	number pigi.Number NOT NULL,
	logMessage CHARACTER VARYING,
	CONSTRAINT Revision_PK PRIMARY KEY(revisionId)
);

CREATE TABLE pigi.Path
(
	"value" CHARACTER VARYING NOT NULL,
	type CHARACTER(1) NOT NULL,
	CONSTRAINT Path_PK PRIMARY KEY("value")
);

CREATE TABLE pigi.RepositoryHasRevision
(
	repositoryId INTEGER NOT NULL,
	revisionId INTEGER NOT NULL,
	CONSTRAINT RepositoryHasRevision_PK PRIMARY KEY(revisionId, repositoryId)
);

CREATE TABLE pigi.RevisionHasPath
(
	revisionId INTEGER NOT NULL,
	path CHARACTER VARYING NOT NULL,
	CONSTRAINT RevisionHasPath_PK PRIMARY KEY(revisionId, path)
);

ALTER TABLE pigi.RepositoryHasRevision ADD CONSTRAINT RepositoryHasRevision_FK1 FOREIGN KEY (repositoryId) REFERENCES pigi.Repository (repositoryId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE pigi.RepositoryHasRevision ADD CONSTRAINT RepositoryHasRevision_FK2 FOREIGN KEY (revisionId) REFERENCES pigi.Revision (revisionId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE pigi.RevisionHasPath ADD CONSTRAINT RevisionHasPath_FK1 FOREIGN KEY (revisionId) REFERENCES pigi.Revision (revisionId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE pigi.RevisionHasPath ADD CONSTRAINT RevisionHasPath_FK2 FOREIGN KEY (path) REFERENCES pigi.Path ("value") ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT WORK;
