
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA ORMModel1 DEFAULT CHARACTER SET UTF8;

SET SCHEMA 'ORMMODEL1';

CREATE DOMAIN ORMModel1.Number AS INTEGER CONSTRAINT Number_Unsigned_Chk CHECK (VALUE >= 0);

CREATE DOMAIN ORMModel1.Type AS CHARACTER(1) CONSTRAINT ValueTypeValueConstraint1 CHECK (VALUE IN ('A, D, M, R'));

CREATE TABLE ORMModel1.ChangedPath
(
	path CHARACTER NOT NULL,
	type ORMModel1.Type NOT NULL,
	number ORMModel1.Number,
	repository CHARACTER VARYING,
	CONSTRAINT ChangedPath_PK PRIMARY KEY(path),
	CONSTRAINT ChangedPath_Revision_MandatoryGroup CHECK (repository IS NOT NULL AND number IS NOT NULL OR repository IS NULL AND number IS NULL)
);

CREATE TABLE ORMModel1.Repository
(
	URL CHARACTER VARYING NOT NULL,
	name CHARACTER VARYING NOT NULL,
	description CHARACTER VARYING,
	CONSTRAINT Repository_PK PRIMARY KEY(URL)
);

CREATE TABLE ORMModel1.Revision
(
	number ORMModel1.Number NOT NULL,
	repository CHARACTER VARYING NOT NULL,
	author CHARACTER VARYING NOT NULL,
	"date" TIMESTAMP NOT NULL,
	CONSTRAINT Revision_PK PRIMARY KEY(repository, number)
);

ALTER TABLE ORMModel1.ChangedPath ADD CONSTRAINT ChangedPath_FK FOREIGN KEY (repository, number) REFERENCES ORMModel1.Revision (repository, number) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORMModel1.Revision ADD CONSTRAINT Revision_FK FOREIGN KEY (repository) REFERENCES ORMModel1.Repository (URL) ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT WORK;
